const BASE = 'dn/connectedIntlProvider'

export const INIT_REQUEST = `${BASE}/INIT_REQUEST`

export const CHANGE_LANGUAGE_REQUEST = `${BASE}/CHANGE_LANGUAGE_REQUEST`
export const CHANGE_LANGUAGE_SUCCESS = `${BASE}/CHANGE_LANGUAGE_SUCCESS`
export const CHANGE_LANGUAGE_FAILURE = `${BASE}/CHANGE_LANGUAGE_FAILURE`
